### ISSUE TITLE
copy&paste token into the configuration

### ISSUE THREAD

**Issue by martin3000** [LaTrappe/HAKA#10]
**Describe the bug**
On linux systems, you cannot paste the HA token into kodi. 

**To Reproduce**
1. Copy the HA token
2. Start Kodi and open the HAKA setup
3. go to the field for the token
4. press Ctrl-v

**Expected behavior**
the copied token is pasted into the field

**Desktop (please complete the following information):**
 - Ubuntu
 - Kodi 18
 - HAKA version 1

**Additional context**
To paste the token, edit the file ~/.kodi/userdata/addon_data/script.program.homeassistant/settings.xml and paste the token and save the file.

**Comment by LaTrappe** [comment]
I see you did already find a work-around by editing the settings file. Another work-around would be to use the Kodi web client. Enable the web-client in the settings menu of Kodi, open it in a browser. Navigate to the HAKA settings and press enter on the token field. In the web interface an input box pops up. Here you paste the token.
