### ISSUE TITLE
cannot enter the HA token 

### ISSUE THREAD

**Issue by rnijenhu** [LaTrappe/HAKA#13]
Running Kodi on my Android TV, got the issue where you cannot enter a token into the token field of the addons configuration page. It's not direct an issue of the plugin but as a result you cannot use the plugin anymore.   

Google is in the transistion to Google remote service 5 (from 4) and the old phone remote app is not working anymore (and removed from the store). Therefore you cannot copy/paste the token using the app. You have to type-in the token and the entire string is not displayed after approx. 25 chars. Tried several apps in the store, all with the same issue related to the newer google remote service. The new remote app (part of google TV) works only when your Android TV also got the new remote service (which is not available yet for my region / Android TV)

Is almost impossible to do without copy/paste or typing without seeing what you type. The google transition takes already a few months, and no idea when it's updated for my region/TV.

Also tried teamviewer, but you have no ctrl-v in kodi to get the data from the clipboard.

Is there an alternative way to do this ?

**Comment by LaTrappe** [comment]
Hi,
you might want to use the Kodi web interface for this. 

[https://kodi.wiki/view/Web_interface](url)

**Comment by rnijenhu** [comment]
I tried, but do I miss something here? cause under settings->general:addon->python.pluginsource I can only enable/disable the plugin. Cannot find the settings page for any of the plugins (only the enable/disable switches)

**Comment by LaTrappe** [comment]
When you have the web interface opened you are able to use the arrows keys on your keyboard to control Kodi. Navigate to the HAKA! token setting and hit enter on your keyboard. The webinterface should now show an input box where you can paste the token in.
