### ISSUE TITLE
move yaml file to addon_data folder

### ISSUE THREAD

**Issue by sanzoghenzo** [LaTrappe/HAKA#17]
**Describe the bug**

If the addon folder is read only for the user (it happens on NixOS, I'm trying to package your addon to be able to install it in a declarative way), the addon cannot be launched because of the following excepton:

```
Traceback (most recent call last):
File "/nix/store/v26056qcd4js4bddpkcbrp5fhfzcsysx-kodi-21.0-env/share/kodi/addons/script.program.homeassistant/addon.py", line 391, in <module>
        open(fileHakaFavourites, 'w').close()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/nix/store/v26056qcd4js4bddpkcbrp5fhfzcsysx-kodi-21.0-env/share/kodi/addons/script.program.homeassistant/hakaFavourites.yaml'
```

This could be solved by (and I think it is a best practice) moving the editable file to the addon_data folder:

```
fileHakaFavourites = os.path.join(Addon.getAddonInfo('profile'), 'hakaFavourites.yaml')
```

**To Reproduce**

I suppose this is a NixOS problem only, but one could emulate this:

1. install the addon
2. configure it
3. recursively set the addon folder permissions to read only
4. launch the addon

**Expected behavior**
The addon should open without the OSError exception

**Desktop (please complete the following information):**
 - OS: NixOS
 - Kodi version 21
 - Home Assistant installation description 2024.5.4 in a docker container + reverse proxy - the connection works
 - HAKA version [e.g. 1.0.0]

**Additional context**

To maintain retrocompatibility, the [file existence check](https://github.com/LaTrappe/HAKA/blob/0b9bd03959c513bfeee9f5ff3002c99313f565b3/addon.py#L373) should also check if the file is present at the old path and copy/move it to the new location.

**Comment by aanderse** [comment]
> I suppose this is a NixOS problem only, but one could emulate this:

if you were attempting to packages this for `ubuntu`, for an example, you would run into the same issue because `/usr/share/kodi/addons/script.program.homeassistant` would be owned by `root:root` and unwritable by the user you run `kodi` as



> This could be solved by (and I think it is a best practice) moving the editable file to the addon_data folder:
> 
> ```
> fileHakaFavourites = os.path.join(Addon.getAddonInfo('profile'), 'hakaFavourites.yaml')
> ```

wonderful! with a few more lines to deal with migration of existing users, as you mentioned, hopefully this wouldn't be a controversial PR... :sweat_smile:

**Comment by LaTrappe** [comment]
Cheers to both. Thanks for pointing this out. I am not actively using or maintaining this anymore, but I am happy to receive a PR.
