### ISSUE TITLE
Compatibility with Kodi 19

### ISSUE THREAD

**Issue by Braincoke** [LaTrappe/HAKA#7]
Not sure if this is expected but the addon does not work with Kodi 19.

The installation seems to work properly but when I try to start the addon I only get an error.

**Log**
addon.py, line 4

import urlparse
ModuleNotFoundError : No module named 'urlparse'

**Desktop**
 - OS: Nvidia Shield
 - Kodi version 19
 - Home Assistant 2021.1.5
 - HAKA version 1.1.0

**Comment by LaTrappe** [comment]
Indeed this is expected behaviour. Kodi 19 (Matrix) version is in development. A first version is to expect in the coming weeks. Thanks for reporting.

**Comment by Braincoke** [comment]
Fair enough.
Thanks for taking the time to answer and for sharing your work :)

**Comment by LaTrappe** [comment]
Please check out the Matrix branch and report any issues if there are [https://github.com/LaTrappe/HAKA/tree/Matrix](url)

**Comment by Braincoke** [comment]
It works perfectly now, thanks
