### ISSUE TITLE
Kodi 19 broken addon due to python2 imports

### ISSUE THREAD

**Issue by pietervanh** [LaTrappe/HAKA#8]
**Describe the bug**
Addon not working in Kodi 19

**To Reproduce**
Open addon in Kodi 19

**Expected behavior**
Should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: android tv
 - Kodi 19.0
 - Home Assistant 2021.2.3 local
 - HAKA version  1.1.0

**Additional context**

Kodi 19 is python3

it fails on import urllib

See [Possible workaround](https://forum.kodi.tv/showthread.php?tid=353208&pid=2938085#pid2938085) to fix it so it would continue working in both 18 and 19.

Great job with the addon, hope to see this in the default xbmc addon repository soon.

**Comment by LaTrappe** [comment]
Hi Pieter, thanks for reporting. As stated on the readme.md a Kodi Matrix version is in development. Unfortunately there's a bit more involved than just the urllib thingy. That said, be assured a Matrix version will be released in the coming weeks.

**Comment by LaTrappe** [comment]
Please check out the version posted on [https://github.com/LaTrappe/HAKA/tree/Matrix](url) and report any issues if there are. Otherwise please close the issue.

**Comment by pietervanh** [comment]
Cool it's working now thanks.
